# \ufe0f Configuraci\u00f3n de MySQL
# Ajustado al nombre que tienes en Workbench: tkoh_tickets
spring.datasource.url=jdbc:mysql://localhost:3306/tkoh_tickets?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=Mysql1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# \ufe0f Configuraci\u00f3n de JPA / Hibernate
# 'update' crear\u00e1 las tablas autom\u00e1ticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto actualizado para MySQL 8+ (Evita warnings de Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# \ud83d\udee1\ufe0f Configuraci\u00f3n de Seguridad y Errores
server.error.include-message=always
spring.main.allow-bean-definition-overriding=true

#  Tama\u00f1o m\u00e1ximo de peticiones
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Cambia el 8080 por 8081
server.port=8081